### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by evanshortiss** [indrimuska/google-maps-api-typings#4]
Hey, I'm seeing this when attempting to run `tsc` on code that uses this module:

```
Error: Cannot find module 'google-maps-api-typings'
```

It compiles fine, but at runtime it fails. I suppose this makes sense since this module has no "main" in package.json, but is there some compiler setting required to work around this?

Sample code:

```ts
import 'google-maps-api-typings'
import * as env from 'env-var'
import * as maps from '@google/maps'
import log from '../log'

const mapsClient = maps.createClient({
  key: env.get('MAP_KEY').required().asString()
})
```

**Comment by evanshortiss** [comment]
FWIW this works as a workaround:

```
/// <reference path="../../node_modules/google-maps-api-typings/index.d.ts" />
import * as env from 'env-var'
import * as maps from '@google/maps'
import log from '../log'

const mapsClient = maps.createClient({
  key: env.get('MAP_KEY').required().asString()
})
```

**Comment by mutsys** [comment]
The issue occurs because the type definition is not in the `@types` scope. So until this project is accepted into DefinitelyTyped repo, you need to "trick" `tsc` into thinking that this type-definition-only project contains a module by adding an empty `index.js` file. This obviates the need for something like @evanshortiss workaround (which requires a hardcoded path to the type def file, yuk) or adding `compilerOptions.typeRoots` to `tsconfig.json` (also yuk because you need to do something special to use this type def even though you acquired it the same way as any other type def). The dummy module file makes this work without any additional configuration beyond declaring it as a dev dependency.

I just submitted a PR that resolves this issue as described.

**Comment by evanshortiss** [comment]
@mutsys I figured your solution (`"main"` in package.json or `index.js`) would work, but assumed I was missing something obvious! Thanks for confirming and patching this.

**Comment by indrimuska** [comment]
Close this in favor of #3
